go.mod, go.sum, pkg/apiclient/default.go, pkg/errors/errors.go
Informs users of missing environment variables at run time: 
- Add hashicorp/multierror
- Add OsEnvironmentError type
- Validation function for NewFromEnvironment
=> feat: Add os env variable validation

.goreleaser.yaml, cmd/octopus/main.go, pkg/cmd/config/get/get.go, pkg/cmd/config/set/set.go, pkg/config/config.go
If you bindEnv/flags etc into viper, then it WILL write them to the config file, by design.
This was already handled by using a secondary viper inside 'config set'; however the global viper would also write the config file on startup as part of it's code to check that the file existed. This is how the env vars leaked into it.
Fix: 
- The global viper can pick up all the env vars and flags and only read. It must NOT write to or create the file
- The local viper inside 'config set' can read, write and create the file, but it must NOT pickup env vars and flags.
Root cause:
The code which created the file as part of reading it was trying to be helpful. It wasn't easy to pick up, as it was nested inside a few layers... Better to be explicit about when the file is created and avoid magic …
=> fix: cli#71 - config system was leaking env vars into the config file when it shouldn't have 

.github/workflows/go-releaser.yml, .goreleaser.yaml, .octopus/deployment_process.ocl, build/tools/chocolateyInstall.ps1
While using `gh` is nice, the fact that we have to maintain a package that contains it (even if that's just getting the package from the release on GitHub and uploading it to Octopus) makes it a less optimal solution.
The script can still be run locally but will only create the PR for the update if you pass in a GitHub PAT.
=> Use the GitHub API instead of the GitHub CLI to create the PR

.github/workflows/go-releaser.yml, .goreleaser.yaml, .octopus/deployment_process.ocl, DISTRIBUTION.md
`goreleaser` has an option to generate a homebrew formula file as part of the `release` command. I've put together this PR as a way of showing the team what output it would produce, if we think it's not appropriate then we can just close it.
The file is more verbose than what is currently in the `octopus-cli.rb` file due to some changes GoReleaser made to their homebrew implementation where they put the `install` definition inside each of the architecture block instead of a single definition towards the end of the file.
Example output of `octopus-cli.rb` running `goreleaser release`:
```
class OctopusCli < Formula
desc "The New CLI (octopus) for Octopus Deploy, a user-friendly DevOps tool for developers that supports release management, deployment automation, and operations runbooks" …
```
=> Generate new homebrew formula file as part of goreleaser release

.octopus/deployment_process.ocl
There was an issue with how the body was being passed to GitHub
```
InvalidOperation: Response status code does not indicate success: 400 (Bad Request). 
September 30th 2022 14:20:47Error
At /home/Octopus/Work/20220930042032-4232676-7759/Script.ps1:47 char:5 
September 30th 2022 14:20:47Error
+     Invoke-RestMethod -Method POST ` 
September 30th 2022 14:20:47Error
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
September 30th 2022 14:20:47Error
at <ScriptBlock>, /home/Octopus/Work/20220930042032-4232676-7759/Script.ps1: line 47 
September 30th 2022 14:20:47Error
at <ScriptBlock>, <No file>: line 1 
September 30th 2022 14:20:47Error
at <ScriptBlock>, /home/Octopus/Work/20220930042032-4232676-7759/Octopus.FunctionAppenderContext.ps1: line 211 
September 30th 2022 14:20:47Error
at <ScriptBlock>, …
```
=> fix: Fix issue when creating PR to update homebrew formula

go.mod, go.sum, pkg/cmd/project/project.go, pkg/cmd/project/view/view.go, pkg/cmd/space/view/view.go, pkg/constants/constants.go
[sc-18973]
Depends on https://github.com/OctopusDeploy/go-octopusdeploy/pull/145
Help output:
```
View a project in an instance of Octopus Deploy
USAGE
octopus project view {<name> | <id> | <slug>} [flags]
FLAGS
-w, --web   Open in web browser
INHERITED FLAGS
-h, --help                   Show help for command
--no-prompt              disable prompting in interactive mode
-f, --output-format string   Output Format (Valid values are 'json', 'table', 'basic'. Defaults to table)
-s, --space string           Set Space
EXAMPLE
$ octopus project view Projects-9000
$ octopus project view 'Deploy Web App'
$ octopus project view deploy-web-app
```
View command output using the `slug` as the project identifier
```
❯ ./octopus project view with-cac -s Default
with cac (Projects-321)
Version control …
```
=> feat: add project view command

go.mod, go.sum, pkg/cmd/account/delete/delete.go, pkg/cmd/environment/delete/delete.go, pkg/cmd/project/delete/delete.go, pkg/cmd/project/project.go, pkg/cmd/space/delete/delete.go, pkg/question/input.go
[sc-26927]
delete via name
delete via slug
delete with confirm
=> feat: project delete

go.mod, go.sum, pkg/cmd/project/delete/delete.go, pkg/cmd/project/view/view.go, pkg/cmd/root/root.go, pkg/cmd/tenant/connect/connect.go, pkg/cmd/tenant/connect/connect_test.go, pkg/cmd/tenant/tenant.go, pkg/executionscommon/executionscommon.go, test/testutil/fakesurvey.go
[sc-27715]
Depends on https://github.com/OctopusDeploy/go-octopusdeploy/pull/154
Project doesn't support tenanted deployments, failure condition:
Project doesn't support tenanted deployments, explicit permission:
Project selection:
With automation command output:
=> feat: tenant connect

pkg/cmd/target/azure-web-app/list/list.go, pkg/cmd/target/cloud-region/list/list.go, pkg/cmd/target/list/list.go, pkg/cmd/target/listening-tentacle/list/list.go, pkg/cmd/target/polling-tentacle/list/list.go, pkg/cmd/target/ssh/list/list.go
Missed adding 'ls' alias to all deployment target list commands
=> fix: deployment-target list alias

go.mod, go.sum, pkg/cmd/target/list/list.go, pkg/cmd/target/target.go, pkg/cmd/target/view/view.go, pkg/cmd/worker/list/list.go, pkg/cmd/worker/listening-tentacle/listening-tentacle.go, pkg/cmd/worker/listening-tentacle/view/view.go, pkg/cmd/worker/polling-tentacle/polling-tentacle.go, pkg/cmd/worker/polling-tentacle/view/view.go, pkg/cmd/worker/shared/view.go, pkg/cmd/worker/ssh/ssh.go, pkg/cmd/worker/ssh/view/view.go, pkg/cmd/worker/view/view.go, pkg/cmd/worker/worker.go
=> feat: worker view

pkg/cmd/root/root.go, pkg/cmd/space/delete/delete.go, pkg/cmd/user/delete/delete.go, pkg/cmd/user/list/list.go, pkg/cmd/user/user.go
Adds simple implementations of `user list` and `user delete`, suitable for enabling deletion of users via a script. More advanced/interactive use-cases may be implemented at some unspecified future time.
=> feat: user list and user delete

pkg/cmd/release/create/create.go
Our example text contained the shortcut for `--version` but we didn't implement it
before:
after:
=> fix version shortcut on release create

pkg/cmd/release/create/create.go, pkg/cmd/release/deploy/deploy.go, pkg/question/selectors/channels.go
there is a redundant prompt if there is only a single channel
before:
after:
=> fix: no prompt if only a single channel

pkg/cmd/target/azure-web-app/create/create.go, pkg/cmd/target/cloud-region/create/create.go, pkg/cmd/target/listening-tentacle/create/create.go, pkg/cmd/target/shared/role.go, pkg/cmd/target/shared/role_test.go, pkg/cmd/target/ssh/create/create.go, pkg/cmd/tenant/list/list.go, pkg/util/util.go, pkg/util/util_test.go
This change is to support filtering tenants by tag using `jq`
json before:
json after:
* note: the change to pull all fields from the api means that we end up with the default json serialisation on the client model. In the case of the Tenants, the `TenantTags` field is marked as `omitempty` so an empty array ends up being left out. Previously we were ending up with the default values of an empty array in the json, making the contract more stable.
table before:
table after:
=> fix: expand tenant view output

pkg/cmd/release/create/create_test.go, pkg/cmd/release/list/list.go, pkg/cmd/release/list/list_test.go
this is to support filtering releases by assembled date. Thought I would include release notes as a xmas gift
json before:
json after:
table before:
table after:
=> fix: extended release output

pkg/cmd/project/convert/convert.go, pkg/cmd/project/convert/convert_test.go, pkg/cmd/project/create/create_opts.go
the config-as-code flag on `project create` was not required during automation, missed in https://github.com/OctopusDeploy/cli/pull/166
before:
after:
The git credentials storage question was asked first, then we didn't prompt for the credentials until the end, credentials are now asked second.
result:
=> chore: cleanup project create

.github/workflows/go-releaser.yml, README.md, pkg/apiclient/client_factory.go, pkg/cmd/config/get/get.go, pkg/cmd/config/list/list.go, pkg/cmd/config/set/set.go, pkg/config/config.go, pkg/constants/constants.go, test/integration/integrationtestutil.go
All of our GitHubAction tooling etc uses `OCTOPUS_URL` for the environment variable name that gives us the base url for the Octopus API.
This PR brings the Go CLI into line with that naming.
=> Fixed the OCTOPUS_URL environment variable name

.github/workflows/go-releaser.yml
Go releaser workflow wasn't updated when the environment variable name was corrected, which meant that the use of the v2 GitHub Actions caused a failure.
This PR upgrades to v3 of the GitHub Actions
=> Fixes for Go Releaser, moving it to Ocotpus' v3 GitHub Actions

go.mod, go.sum, pkg/cmd/project/convert/convert.go, pkg/cmd/project/convert/convert_test.go, pkg/cmd/release/create/create_test.go, test/fixtures/projects.go
convert a project without supplying values for default branch, initial commit branch, initial commit message
seems like you cannot use the same branch multiple times even if it has been deleted in Github
=> fix: remove project convert support for default protected branch 

pkg/cmd/account/aws/create/create.go, pkg/cmd/account/aws/create/create_test.go, pkg/cmd/account/azure/create/create.go, pkg/cmd/account/azure/create/create_test.go, pkg/cmd/account/create/create.go, pkg/cmd/account/gcp/create/create.go, pkg/cmd/account/gcp/create/create_test.go, pkg/cmd/account/ssh/create/create.go, pkg/cmd/account/ssh/create/create_test.go, pkg/cmd/account/token/create/create.go, pkg/cmd/account/token/create/create_test.go, pkg/cmd/account/username/create/create.go, pkg/cmd/account/username/create/create_test.go, pkg/cmd/target/shared/environment.go, pkg/question/selectors/environments.go
Fixes https://github.com/OctopusDeploy/cli/issues/205
This PR also consolidates a lot of repeated code for create new options structs plus cleans up repeated properties to use shared structs for dependencies on a command
=> chore: fix null ref in general account create command

.github/workflows/go-releaser.yml, .github/workflows/integration-test.yml, .github/workflows/pr-validation.yml
[sc-41298]
This change creates a PR with the latest releases as releases.json in the repository. This is to avoid rate limiting on the install-octopus-cli steps for both GH actions and ADO. Tokens can be used to avoid rate limiting. However, this isn't viable as GH branch protections prevent generic public tokens from accessing our releases. These tokens are also not generated automatically in ADO so instead this approach allows us to use `https://raw.githubusercontent.com/OctopusDeploy/cli/releases.json` which is not rate limited.
Functionality and generated PR tested on https://github.com/OctopusDeploy/Isaac-Actions-Test/pull/19. I didn't have access to gpg keys etc [to test e2e](https://github.com/OctopusDeploy/Isaac-Actions-Test/actions/runs/4911571245/jobs/8769726720), however am …
=> Update releases.json on new release created/published. 

pkg/cmd/release/create/create.go, pkg/cmd/release/create/create_test.go, pkg/cmd/release/deploy/deploy.go, pkg/cmd/release/deploy/deploy_test.go
fixes #229 
[sc-48988]
before: 
```
octopus release create -p bulk-project-1 -c default -s "bulk project" --no-prompt
Octopus API error: Project named 'bulk-project-1' was not found. []
```
```
octopus release deploy -s Spaces-123 -p bulk-project-1 --version 0.0.6 -e "test 1" --no-prompt
Octopus API error: Project named 'bulk-project-1' was not found. []
```
after:
```
octopus release create -p bulk-project-1 -c default -s Spaces-123 -v 0.0.7 --no-prompt
Successfully created release version 0.0.7 using channel Default
View this release on Octopus Deploy: http://localhost:8065/app#/Spaces-123/releases/Releases-3522
```
```
octopus release deploy -s Spaces-123 -p bulk-project-1 --version 0.0.6 -e "test 1" --no-prompt
Successfully started 1 deployment(s)
```
=> fix: added support for project slugs to release commands

.github/workflows/go-releaser.yml
GH action update-releases.json is failing when creating a PR due to GITHUB_TOKEN permissions. INTEGRATIONS_TOKEN has these permissions and is being used instead. See Create_PR - https://github.com/OctopusDeploy/cli/actions/runs/5040370886/jobs/9039191314
I've attempted to confirm this will not hit other organisation restrictions over in [my test project ](https://github.com/OctopusDeploy/Isaac-Actions-Test/pulls), however am waiting on approval for my OctopusDeploy organisation scoped token.
=> Use Integrations Token over GHA Token for PR permissions

.github/workflows/generate-docs.yml
The docs recently had a restructure and the path the the cli pages changed
https://github.com/OctopusDeploy/docs/tree/main/src/pages/docs/octopus-rest-api/cli
=> updated docs path

.github/workflows/generate-docs.yml
Another broken path in the `generate docs` workflow
Ran against this branch and it produced this docs pr https://github.com/OctopusDeploy/docs/pull/1908/files
=> chore: updated action workflow file

go.mod, go.sum, pkg/cmd/project/branch/branch.go, pkg/cmd/project/branch/create/create.go, pkg/cmd/project/branch/create/create_test.go, pkg/cmd/project/branch/list/list.go, pkg/cmd/project/branch/shared/shared.go, pkg/cmd/project/project.go, pkg/cmd/project/variables/create/create.go, pkg/cmd/project/variables/create/create_test.go, pkg/cmd/project/variables/list/list.go, pkg/cmd/project/variables/update/update.go, pkg/cmd/project/variables/update/update_test.go, pkg/question/shared/variables/variables.go
Depends upon https://github.com/OctopusDeploy/go-octopusdeploy/pull/198
Fixes: #252 
Branches:
Create new branch for project:
```
❯ octopus project branch create -p "cac project" --base-branch refs/heads/main --name second-branch
Successfully created branch 'second-branch' (refs/heads/second-branch) in project 'Cac project'
Automation Command: octopus project branch create --project 'cac project' --name 'second-branch' --base-branch 'refs/heads/main' --no-prompt
```
List branches for project:
```
❯ octopus project branch list -p "cac project"
NAME           CANONICAL NAME            IS PROTECTED
main           refs/heads/main           false
second-branch  refs/heads/second-branch  false
```
Create variable on CaC branch:
```
❯ octopus project variable create -p "cac project" --git-ref …
```
=> feat: project variable git support

.goreleaser.yaml
archives replacements has been deprecated - https://goreleaser.com/deprecations/#archivesreplacements
=> fixed go-releaser due to deprecated feature

pkg/cmd/project/convert/convert.go
fixes #222 
before: 
```
❯ octopus project create --process-vcs -n ${PWD##*/} -l "Default Lifecycle"  -g "Default Project Group" --git-url $(git config --get remote.origin.url) --git-credentials git-creds --git-credential-store "Library" -s Default
? Git username [? for help]
interrupt
```
after:
```
❯ octopus project create --process-vcs -n ${PWD##*/} -l "Default Lifecycle"  -g "Default Project Group" --git-url $(git config --get remote.origin.url) --git-credentials git-creds --git-credential-store "Library" -s Default
? Git repository base path .octopus/octopus
? Git branch main
? Enter a protected branch pattern (enter blank to end)
? Initial Git commit message Initial commit of deployment process
Successfully created project 'octopus' (octopus), with lifecycle 'Default Lifecycle' in …
```
=> fix: prompt checks for git credentials storage was case-sensitive

go.mod, go.sum, pkg/apiclient/apiclient_test.go, pkg/apiclient/client_factory.go, pkg/apiclient/client_factory_test.go, pkg/config/config.go, pkg/constants/constants.go, test/testutil/fakeoctopusserver.go
This PR adds support for authenticating using an access token as a bearer token in the `Authorization` header. Access tokens are obtained using OpenID Connect and by nature are short-lived. As such, storing access tokens in the cli configuration (`octopus config set`) is not supported, and are only read from the `OCTOPUS_ACCESS_TOKEN` environment variable. This environment variable will be set automatically when using the `OctopusDeploy/login` action which is currently only released internally.
Note: This PR requires https://github.com/OctopusDeploy/go-octopusdeploy/pull/201 to be completed and a new version of the `go-octopusdeploy` client to be released before it will build. Update: This PR is merged now.
Note: The OpenID Connect feature is currently under development and may not be …
=> feat: Adds support for authenticating with access token

pkg/cmd/worker/list/list.go
The fields that are included in the JSON output in `worker list` and `worker view` commands differ. 
This PR updates the `worker list` output to match that of the `worker view` output.
Before
```
octopus worker list --space Default -f json | jq '.[] | select(.Name == "WorkerL0")'
{
"Id": "Workers-1",
"Name": "WorkerL0",
"Type": "TentaclePassive",
"WorkerPools": [
{
"Id": "WorkerPools-1",
"Name": "Default Worker Pool"
}
]
}
```
After
```
octopus worker list --space Default -f json | jq '.[] | select(.Name == "WorkerL0")'
{
"Id": "Workers-1",
"Name": "WorkerL0",
"Type": "TentaclePassive",
"HealthStatus": "Healthy",
"StatusSummary": "Octopus was able to successfully establish a connection with this machine on Tuesday, 31 October 2023 12:06:43 pm +10:00",
"WorkerPools": [
{
"Id": …
```
=> Update fields included in JSON output for workers list

pkg/cmd/worker/list/list.go, pkg/cmd/worker/ssh/view/view.go
I missed adding URI, Tentacle version, SSH runtime architecture, Account and Proxy details to the JSON output when listing workers in #284.
This PR adds these additional fields.
```
octopus worker list --space Default --output-format json | jq '.[] | select(.Name == "WorkerL0")'
{
"Id": "Workers-1",
"Name": "WorkerL0",
"Type": "TentaclePassive",
"HealthStatus": "Healthy",
"StatusSummary": "Octopus was able to successfully establish a connection with this machine on Tuesday, 31 October 2023 12:06:43 pm +10:00",
"WorkerPools": [
{
"Id": "WorkerPools-1",
"Name": "Default Worker Pool"
}
],
"URI": "https://localhost:10000/",
"Version": "0.0.0-local",
"Proxy": "None"
}
```
```
octopus worker list --space Default --output-format json | jq '.[] | select(.Name == "SshWorker")'
{
"Id": …
```
=> Add additional fields to json output when listing workers

README.md
It's been quite some time since this readme was written and a large number of features that the .NET CLI has have now been implemented and we also have documentation hosted in on our website.
=> Add link to Octopus docs in the readme

cmd/gen-docs/main.go
to fix error in docs-gen
```
Error: cmd/gen-docs/main.go:99:50: not enough arguments in call to factory.New
have (apiclient.ClientFactory, question.AskProvider, *spinner.Spinner, string)
want (apiclient.ClientFactory, question.AskProvider, factory.Spinner, string, "github.com/OctopusDeploy/cli/pkg/config".IConfigProvider)
Error: Process completed with exit code 1.
```
=> fixed factory method parameters

pkg/cmd/tenant/list/list.go, pkg/cmd/tenant/shared/shared.go, pkg/cmd/tenant/view/view.go, pkg/output/print_resource.go, pkg/output/shared.go
This PR introduces a new helper method to add support for output formatting for `view` commands, similar to what there is for `list` commands.
This PR also converts the `tenant view` command to use this new formatting helper. Output below:
**Default (Table) output formatting**
```
❯ ./octopus tenant view "Tenant A" --space Default
NAME      DESCRIPTION  ID           TAGS
Tenant A               Tenants-301  Test/Foo, Hosting/Shared
```
**Basic output formatting**
```
❯ ./octopus tenant view "Tenant A" --space Default -f basic
Tenant A (Tenants-301)
Tags: Test/Foo, Hosting/Shared
No description provided
http://localhost:8065/app#/Spaces-1/tenants/Tenants-301/overview
View this tenant in Octopus Deploy: http://localhost:8065/app#/Spaces-1/tenants/Tenants-301/overview
```
**JSON output …
=> Tenant view command support for output formatting

README.md
Removing the use of deprecated apt-key command in our default install instructions
=> Updating Ubuntu/Debian Install Commands

.github/workflows/integration-test.yml, pkg/apiclient/client_factory.go, pkg/apiclient/requester.go, test/testutil/fakefactory.go, test/testutil/fakeoctopusserver.go, test/testutil/fakesurvey.go, test/testutil/testutil.go
I found that the tests didn't build or run locally because "slices" in `fakesurvey.go` didn't exist; the package name was wrong or had changed.
I fixed that, and a few other small lint warnings while I had it open. I verified all tests pass including integration tests.
I also changed the docker image the tests are using over to the official one on dockerhub rather than our internal docker.packages.octopushq.com -- dockerhub is faster, and we only need the internal one if we are targeting some feature that has not been released to GA self-host customers yet; which is not currently the case.
=> chore: Fix small error and warnings in tests, use dockerhub for octopus server image rather than packages.octopushq

pkg/cmd/environment/create/create.go, pkg/cmd/environment/environment.go
Fixes: #268 
with some prompts:
```
❯ octopus environment create -n "from cli 5" -s default
? Description
? Use guided failure Yes
? Allow dynamic infrastructure Yes
Successfully created environment from cli 5 (Environments-306).
View this environment on Octopus Deploy: http://localhost:8066/app#/Spaces-1/infrastructure/environments/Environments-306
```
with all parameters:
```
❯ octopus environment create -n "from cli 6" -s default -d "description" --use-guided-failure --allow-dynamic-infrastructure
Successfully created environment 'from cli 6' (Environments-309).
View this environment on Octopus Deploy: http://localhost:8066/app#/Spaces-1/infrastructure/environments/Environments-309
octopus environment create --name 'from cli 6' --description 'description' --use-guided-failure …
```
=> feat: environment create

go.mod, pkg/cmd/runbook/runbook.go, pkg/cmd/runbook/snapshot/list/list.go, pkg/cmd/runbook/snapshot/snapshot.go, pkg/question/selectors/runbooks.go
with selectors, one runbook
```
❯ octopus runbook snapshot list -s default -f json
? Select the project to list runbook snapshots for just runbooks
[
{
"Id": "RunbookSnapshots-123",
"Name": "Snapshot 68G5LE7",
"Assembled": "2024-03-12T04:43:06.083Z"
},
{
"Id": "RunbookSnapshots-122",
"Name": "Snapshot 7KX8P9X",
"Assembled": "2024-03-12T04:42:43.243Z"
}
]
```
with multiple runbooks in project:
```
❯ octopus runbook snapshot list -s default
? Select the project to list runbook snapshots for project-49f8539a-eb71-441d-ab19-19e55ab4ec29
? Select the runbook to list snapshots for runbook 2
ID                    NAME              ASSEMBLED
RunbookSnapshots-124  Snapshot GW1NUT5  Tue, 12 Mar 2024 06:31:03 +0000
```
json output 
```
❯ octopus runbook snapshot list -s default -p just-runbooks -r …
```
=> feat: runbook snapshot list

pkg/cmd/runbook/delete/delete.go, pkg/cmd/runbook/runbook.go, pkg/cmd/runbook/shared/shared.go, pkg/question/selectors/runbooks.go
listing runbooks
```
❯ octopus runbook list -s default -p just-runbooks
Project just runbooks
NAME       DESCRIPTION
runbook
runbook-2
```
delete with prompts and confirmation
```
❯ octopus runbook delete -s default
? Select the project containing the runbook you wish to delete: just runbooks
? Select the runbook you wish to delete: runbook-2
? You are about to delete the runbook "runbook-2" (Runbooks-144). This action cannot be reversed. To confirm, type the runbook name: runbook-2
✔ The runbook, "runbook-2" (Runbooks-144) was deleted successfully.
```
delete with confirmation parameter
```
❯ octopus runbook delete -s default -p just-runbooks -r "runbook-2" --confirm
❯ octopus runbook list -s default -p just-runbooks
Project just runbooks
NAME     DESCRIPTION
runbook
```
=> feat: runbook delete

pkg/cmd/release/deploy/deploy.go, pkg/cmd/release/deploy/deploy_test.go
When deploying a release with required variables, we ask the user for values via the command line.
Previously the order of these variables was not deterministic, causing the related test to be flakey.
I've now sorted these variable controls alphabetically, which will fix the flakey test and provide a more consistent UX.
[sc-76938]
=> Order interactive variables by name when deploying releases

pkg/machinescommon/web.go
Before:
```
Successfully created Azure web app 'webapp-ben-3'.
View this Azure web app on Octopus Deploy: http://localhost:8066/app#/Spaces-383/infrastructure/machines/Machines-11241
```
After:
```
Successfully created Azure web app 'webapp-ben-4'.
View this Azure web app on Octopus Deploy: http://localhost:8066/app#/Spaces-383/infrastructure/machines/Machines-11243/settings
```
=> fix: wrong url for new infrastructure

.github/workflows/go-releaser.yml
`rm-dist` has been deprecated https://goreleaser.com/deprecations/#-rm-dist
=> chore: fixed go-releaser deprecated option

.goreleaser.yaml
Further deprecations for updating to go-releaser v2, which we had no control over 😞 
`changelog.skip` replaced with `changelog.disable`: https://goreleaser.com/deprecations/#changelogskip
`brews.tap` replaced with `brews.repository`:  https://goreleaser.com/deprecations/#brewstap
=> chore: further fixes for go-releaser deprecations

go.mod, go.sum, pkg/cmd/buildinformation/build-information.go, pkg/cmd/buildinformation/upload/upload.go, pkg/cmd/root/root.go
This PR adds a command to upload build information to Octopus.
```
octopus build-information upload --package-id ThePackage --version 1.2.3 --file /path/to/octopus/buildinformation/file.json --overwrite-mode ignore
```
```
octopus build-info upload ThePackage --version 1.2.3 --file /path/to/octopus/buildinfo/file.json --overwrite-mode fail
```
[sc-83928]
=> feat: add upload build info command

go.mod, go.sum, pkg/cmd/buildinformation/build-information.go, pkg/cmd/buildinformation/list/list.go
List all build information
```
octopus build-information list
octopus build-info ls
```
List only latest build information for all packages
```
octopus build-info ls --latest
```
List all build information for a specific package id
```
octopus build-info ls --package-id ThePackage
```
List only latest build information for a specific package id
```
octopus build-info ls --package-id --latest
```
default (table) output
```
$ octopus build-info ls --package-id package-11383 --latest --output-format table
PACKAGE ID     VERSION   ENVIRONMENT  BUILD NO  BRANCH  COMMITS  WORKITEMS
package-11383  0.1.1000  BitBucket    288       main    3        0
```
json output
```
$ octopus build-info ls --package-id package-11383 --output-format json --latest
[
{
"Id": "BuildInformation-7000",
"PackageId": …
```
=> feat: add list build information command

pkg/cmd/buildinformation/build-information.go, pkg/cmd/buildinformation/delete/delete.go
_Builds on #366 so that should be reviewed and merged first._
Delete build information command
```
$ octopus build-information delete
$ octopus build-info rm
$ octopus build-info del
```
Delete build information by id
```
$ octopus build-info rm BuildInformation-10004
? You are about to delete the build information "TheOtherPackage 1.2.5" (BuildInformation-10004). This action cannot be reversed. To confirm, type the build information name: TheOtherPackage 1.2.5
✔ The build information, "TheOtherPackage 1.2.5" (BuildInformation-10004) was deleted successfully.
```
Delete build information using package id and version
```
$ octopus build-info rm --package-id ThePackage --version 1.2.3
? You are about to delete the build information "ThePackage 1.2.3" (BuildInformation-10001). This action …
```
=> feat: add delete build information command

pkg/cmd/buildinformation/build-information.go, pkg/cmd/buildinformation/bulkdelete/bulk-delete.go
Bulk delete build information command
```
// delete all build information for a package id
$ octopus build-information bulk-delete --package-id ThePackage
// delete specific build information for a package id
$ octopus build-info bulk-delete --package-id ThePackage --version 1.2.3 --version 1.2.4 --version 1.2.5
```
delete all build information for a package id
```
$ octopus build-info bulk-delete
? Select the Package ID you wish to delete: TheOtherPackage
? Select versions to delete? No
? You are about to delete the following build information BuildInformation-10010. This action cannot be reversed. To confirm, type 'delete': delete
✔ The BuildInformation-10010 were deleted successfully.
```
delete selected versions of build information for a package id
```
$ octopus build-info …
```
=> feat: add bulk delete build information command

pkg/cmd/buildinformation/upload/upload.go
=> chore: write a warning if build info contains 200 or more commits

pkg/cmd/buildinformation/list/list.go
Accidentally specified `List` rather than `list` as the command name
=> fix: fix command use value as it was capitalised

pkg/cmd/channel/channel.go, pkg/cmd/channel/create/create.go, pkg/cmd/root/root.go, pkg/question/selectors/lifecycles.go
```
$ octopus channel create
? Name Testing
? Select the project in which the channel will be created Test project
? Description
? Select the lifecycle to use for the channel Default Lifecycle
? Set channel as default No
Successfully created channel 'Testing', (Channels-5).
View this channel on Octopus Deploy: https://henrik-buildinfo-testing.testoctopus.app/app#/Spaces-1/projects/Projects-1/deployments/channels/edit/Channels-5
octopus channel create --name 'Testing' --project 'Test project' --lifecycle 'Default Lifecycle' --no-prompt
```
[sc-83931]
=> feat: add create channel command

go.mod, go.sum, pkg/cmd/package/delete/delete.go, pkg/cmd/package/package.go
Depends on https://github.com/OctopusDeploy/go-octopusdeploy/pull/260
delete with no arguments
```
$ octopus package delete
? Select the package you wish to delete: toolscripts
? Select the version you wish to delete: 0.0.3
? You are about to delete the package "toolscripts 0.0.3" (packages-toolscripts.0.0.3). This action cannot be reversed. To confirm, type the package identity (toolscripts 0.0.3): toolscripts 0.0.3
✔ The package, "toolscripts 0.0.3" (packages-toolscripts.0.0.3) was deleted successfully.
```
delete with package specified
```
$ octopus package delete --package-id toolscripts
? You are about to delete the package "toolscripts 0.0.3" (packages-toolscripts.0.0.3). This action cannot be reversed. To confirm, type the package name: toolscripts 0.0.3
✔ The package, "toolscripts …
```
=> feat: add delete package command

go.mod, go.sum, pkg/cmd/release/progression/allow/allow.go, pkg/cmd/release/progression/prevent/prevent.go, pkg/cmd/release/progression/progression.go, pkg/cmd/release/progression/shared/shared.go, pkg/cmd/release/release.go, pkg/util/util.go
This PR adds the following commands to allow managing the progression of releases in Octopus:
- `octopus release progression allow`
- `octopus release progression prevent`
```
$ octopus release progression allow --project 'Available Function App Locations' --version '0.0.4' --no-prompt
Successfully allowed progression for release 0.0.4 (Releases-1686) in project Available Function App Locations
$ octopus release progression allow --project 'Available Function App Locations' --version '0.0.4' --no-prompt
Release with version/release number '0.0.4' (Releases-1686) is already allowed to progress to the next phase.
$ octopus release progression prevent
? Selected the project in which the release to be blocked exists Available Function App Locations
? Select Release to Prevent Progression for …
```
=> feat: add commands to manage release progression

README.md
Version `2.7.0` was added to winget in https://github.com/microsoft/winget-pkgs/pull/172549
=> Add winget as supported installation process on Windows

cmd/octopus/main.go, pkg/cmd/root/root.go
fixes #269 
other commands still work
=> feat: support --version flag

pkg/cmd/root/root.go
`2.8.0` included #391, however, if you just do `octopus` with no args, it no longer prints the root help output.
`2.7.0`
`2.8.0`
Fixed
This PR fixes that by returning `Help` from the root command if the version parameter is not set (previously it was returning `nil`)
=> fix: no program args now outputs the root help again

.octopus/deployment_process.ocl
Uses the [winget-create](https://github.com/microsoft/winget-create) tool to create a new update of the `OctopusDeploy.Cli` manifests.
I also updated the RPM & APT steps to pull the `publish-linux` via Artifactory to avoid Docker rate-limiting issues (as Artifactory will cache the image). This is not a long term plan, but just alleviates the current issue.
I can't really test this, so will wait for the next release of the CLI to see the results
=> Update deployment process to publish updates to winget

pkg/cmd/task/wait/wait.go, pkg/cmd/task/wait/wait_test.go
Checks for `FinishedSuccessfully`, and returns an error for non-successful tasks. The error message used comes from the C# implementation ("One or more deployment tasks failed.").
Fixes #390.
By adding more tests to `task wait`, the test runtime has increased quite a bit due to `time.Sleep(5 * time.Second)`. I would like some input on this. I could potentially replace it with a mock timer to speed things back up. The overhead of adding more tests to `task wait` is pretty significant currently 😅
=> feat: handle failures in task wait

pkg/cmd/release/create/create.go
```
❯ octopus release create --space Default --project "Test function" --version 0.0.36 --output-format json --package "henrik-test-function:0.0.1" --release-notes "test release notes" --no-prompt
{"ReleaseNotes":"","Assembled":"0001-01-01T00:00:00Z","Channel":"Default","Version":"0.0.36"}
```
```
❯ ./octopus release create --space Default --project "Test function" --version 0.0.37 --output-format json --package "henrik-test-function:0.0.1" --release-notes "test release notes" --no-prompt
{"ReleaseNotes":"test release notes","Assembled":"2024-09-18T14:49:56.675+10:00","Channel":"Default","Version":"0.0.37"}
```
[sc-93329]
=> fix: include release notes and assembled date in json output after creating a release

pkg/cmd/task/wait/wait.go, pkg/cmd/task/wait/wait_test.go
Handles non-nil `FinishedSuccessfully` in non-completed tasks by checking if the task is completed first before adding to list of failed tasks.
Fixes #421.
=> fix: handle non-nil fields in task wait

pkg/cmd/space/create/create.go
Do not prompt for existing space when creating a new space.
[sc-73470]
=> Do not prompt for space name (for client) on space creation

pkg/cmd/tenant/variables/list/list.go, pkg/cmd/tenant/variables/update/update.go, pkg/cmd/tenant/variables/variables.go
fixes #429 
source: https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1728463789072219
=> fix: correct help text in tenant variable commands

go.mod, go.sum, pkg/cmd/release/create/create.go, pkg/cmd/release/create/create_test.go
This PR adds support to release creation for detecting when a package reference in a step has been configured with a fixed version. This feature is currently rolling out through Octopus Cloud. If a fixed version is configured on the step then the CLI will no longer attempt to get a version from the feed or ask the user to confirm the version.
This PR needs https://github.com/OctopusDeploy/go-octopusdeploy/pull/276 to be merged and a new version of the library made available.
=> feat: Add support for fixed package versions in release creation

pkg/cmd/tenant/disable/disable.go, pkg/cmd/tenant/enable/enable.go
Generating docs for CLI resulted in incorrect docs for `tenant enable` and `tenant disable` - https://github.com/OctopusDeploy/docs/pull/2565
Fix this by updating `Use` and `Example` to include  the name/id argument.
=> fix: disable/enable tenant command docs

.github/workflows/go-releaser.yml
`upload-artifact/v4` doesn't allow upload artifacts to the same name. We were using this to build a `.zip` file with all the artifacts.
The solution is to copy the MSI into the `artifacts` folder (which was downloaded from earlier), then re-upload with `overwrite` which should give us the full `.zip`
=> Fix uploading of artifacts

go.mod, go.sum, pkg/cmd/tenant/variables/list/list.go, pkg/util/featuretoggle/feature_toggles.go
[SC-93474]
When scoped tenant common variables are enabled, both common and project variables can be scoped by multiple environments. This PR provides support for variables with an array of environment scopes.
Tenant common variables had no environment scoping, so Environment was blank. Project variables were only scoped to one environment, so per template, one row existed per environment.
```
$ ./octopus tenant variables list "t1"
NAME                        LABEL         TYPE     OWNER                    ENVIRONMENT  VALUE                   SENSITIVE  DEFAULT VALUE
template1                                 Library  set1                                  default                 false      true
secret template                           Library  set1                                  *** …
```
=> List scoped common variables

pkg/cmd/tenant/variables/update/update.go, pkg/cmd/tenant/variables/update/update_test.go
[SC-104889]
When updating `project template 1` for project `p2`, values for `p1` `project template 1` and `project template 2` were deleted because they were missing from the POST.
When updating template `common template 2` for variable set `common set 2`, values for `common template 1`, `common set 1` were deleted because they were missing from the POST.
No variables are deleted by the CLI.
=> Fix deleting variables from other variable sets

pkg/cmd/package/nuget/create/create.go
Fixes #510 
Tested that nuspec outputs the expected title property
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
<metadata>
<id>MyPackage</id>
<version>1.2.34</version>
<title>My title</title>
<description>A deployment package created from files on disk.</description>
<authors>Me</authors>
</metadata>
</package>
```
=> Add missing title property to nuspec

go.mod, go.sum, pkg/cmd/runbook/delete/delete.go, pkg/cmd/runbook/list/list.go, pkg/cmd/runbook/run/run.go, pkg/cmd/runbook/shared/shared.go, pkg/cmd/runbook/snapshot/create/create.go, pkg/cmd/runbook/snapshot/list/list.go, pkg/cmd/runbook/snapshot/publish/publish.go, pkg/cmd/runbook/snapshot/snapshot.go, pkg/util/util.go
feat: runbook snapshot publish
fix: runbook snapshot list now shows which snapshot is published
replaces #343 
fixes #110 
Now specifies which snapshot is the current published snapshot
```
ID                    NAME              PUBLISHED  ASSEMBLED
RunbookSnapshots-381  Snapshot 4E6TUYP             Wed, 30 Apr 2025 06:17:16 +0000
RunbookSnapshots-379  Snapshot K8MM6GD             Wed, 30 Apr 2025 01:20:53 +0000
RunbookSnapshots-378  Snapshot 2BRT8ZF             Wed, 30 Apr 2025 01:19:53 +0000
RunbookSnapshots-377  Snapshot 8EKKDY9             Wed, 30 Apr 2025 01:11:29 +0000
RunbookSnapshots-376  Snapshot 3JDLKHP             Wed, 30 Apr 2025 01:11:13 +0000
RunbookSnapshots-375  Snapshot BRYFKMB             Wed, 30 Apr 2025 01:10:10 +0000
RunbookSnapshots-374  Snapshot 40C9ENM …
```
=> feat: runbook snapshot create

.octopus/deployment_process.ocl, pkg/cmd/release/deploy/deploy_test.go
We've discovered if the fork repo is too out of sync, the `winget-create update` call can fail.
This change deletes the fork repo before `update` call runs, which will re-fork the repo as part of it's execution
=> Delete winget-pkgs fork before running winget-create

go.mod, go.sum, pkg/cmd/release/deploy/deploy.go, pkg/cmd/release/deploy/deploy_test.go
Adds missing packages warning when deploying a release. User can continue to deploy if they wish, and if the `--no-
prompt` flag is passed it bypasses this check (as no questions are asked).
This is sitting behind a feature flag.
Requires https://github.com/OctopusDeploy/go-octopusdeploy/pull/335
[sc-110366]
=> feat: warn about missing packages

pkg/cmd/release/deploy/deploy_test.go
[SC-121396]
Tests in deploy_test.go seem to have been flaky for a while. This appears to be a timing issue in the test. Sometimes "Additional Options" were included in the output prior to the buffer being cleared via `stdout.Reset()`, resulting in a failed equals assertion on project name and release number.
Example failure: https://github.com/OctopusDeploy/cli/actions/runs/17413265554/job/49435474443
=> Fix flaky test
