OctopusDeploy/cli

cmd/octopus/main.go

Use survey's terminal.NewAnsiStdout to get colors to work in windows cmd.exe

---

pkg/cmd/config/set/set.go

octopus config set interactive mode broken

---

.gitignore
pkg/cmd/environment/environment.go
pkg/cmd/environment/list/list.go
pkg/cmd/project/list/list.go
pkg/cmd/project/project.go
pkg/cmd/root/root.go

add project list command

---

pkg/cmd/root/root.go
pkg/cmd/tenant/list/list.go
pkg/cmd/tenant/tenant.go

[sc-27733]
table output:
json output:
basic output:

feat: tenant list

---

pkg/cmd/project/connect-tenant/connect-tenant.go
pkg/cmd/project/project.go
pkg/cmd/tenant/connect/connect.go

[sc-27715]
Simply a project command wrapping the `tenant connect` command

feat: project connect-tenant

---

pkg/cmd/project/list/list.go
pkg/cmd/projectgroup/list/list.go
pkg/cmd/projectgroup/project-group.go

feat: project-group list

---

go.mod
go.sum
pkg/cmd/project/view/view.go
pkg/cmd/projectgroup/project-group.go
pkg/cmd/projectgroup/view/view.go

[sc-26921]
view with web link
with web flag

feat: project-group view

---

pkg/cmd/dependencies.go
pkg/cmd/projectgroup/create/create.go
pkg/cmd/space/create/create.go
pkg/cmd/space/create/create_test.go
pkg/cmd/tenant/shared/shared.go

chore: fix space create flags

---

go.mod
go.sum
pkg/cmd/project/create/create.go
pkg/cmd/project/create/create_opts.go
pkg/cmd/project/view/view.go
pkg/cmd/release/create/create.go
pkg/cmd/release/create/create_test.go
pkg/cmd/target/listening-tentacle/create/create_test.go
test/fixtures/projects.go

create project is still working
project view is still working

chore: update go-octopusdeploy library reference

---

pkg/cmd/target/listening-tentacle/create/create.go
pkg/cmd/target/shared/proxy.go
pkg/cmd/target/ssh/create/create.go
pkg/cmd/target/ssh/create/create_test.go
pkg/cmd/target/ssh/ssh.go
pkg/cmd/target/target.go
pkg/question/selectors/selectors.go
pkg/util/flag/flag.go
pkg/validation/validation.go
test/testutil/fakesurvey.go

[sc-29783]
help:
full interactive:
fully automated:

feat: create ssh deployment target

---

go.mod
go.sum
pkg/cmd/target/azure-web-app/azure-web-app.go
pkg/cmd/target/azure-web-app/view/view.go
pkg/cmd/target/cloud-region/cloud-region.go
pkg/cmd/target/cloud-region/view/view.go
pkg/cmd/target/listening-tentacle/listening-tentacle.go
pkg/cmd/target/listening-tentacle/view/view.go
pkg/cmd/target/polling-tentacle/polling-tentacle.go
pkg/cmd/target/polling-tentacle/view/view.go
pkg/cmd/target/shared/view.go
pkg/cmd/target/ssh/ssh.go
pkg/cmd/target/ssh/view/view.go
pkg/cmd/target/target.go
pkg/cmd/target/view/view.go

[sc-6874]
depends on https://github.com/OctopusDeploy/go-octopusdeploy/pull/161
feat: deployment-target azure-web-app view
feat: deployment-target cloud-region view
feat: deployment-target listening-tentacle view
feat: deployment-target ssh view
feat: deployment-target polling-tentacle view
azure web app:
offline drop:

feat: deployment-target view

---

go.mod
go.sum
pkg/cmd/root/root.go
pkg/cmd/target/azure-web-app/create/create.go
pkg/cmd/target/cloud-region/create/create.go
pkg/cmd/target/listening-tentacle/create/create.go
pkg/cmd/target/listening-tentacle/listening-tentacle.go
pkg/cmd/target/shared/web.go
pkg/cmd/target/shared/workerpool.go
pkg/cmd/target/shared/workerpool_test.go
pkg/cmd/target/ssh/create/create.go
pkg/cmd/worker/listening-tentacle/create/create.go
pkg/cmd/worker/listening-tentacle/listening-tentacle.go
pkg/cmd/worker/shared/workerpool.go
pkg/cmd/worker/shared/workerpool_test.go
pkg/cmd/worker/ssh/create/create.go
pkg/cmd/worker/ssh/ssh.go
pkg/cmd/worker/worker.go
pkg/machinescommon/machinepolicy.go
pkg/machinescommon/machinepolicy_test.go
pkg/machinescommon/proxy.go
pkg/machinescommon/proxy_test.go
pkg/machinescommon/web.go

feat: worker ssh create
[sc-29479]
ssh help:
ssh create interactive:
ssh create automation:
listening tentacle create help
listening-tentacle create interactive
listening tentacle create automation

feat: worker listening-tentacle create

---

test/integration/release_test.go

Green Run: https://github.com/OctopusDeploy/cli/actions/runs/3578845905

chore: release list default fix

---

go.mod
go.sum
pkg/cmd/projectgroup/create/create.go
pkg/cmd/space/create/create.go
pkg/cmd/tenant/create/create.go
pkg/cmd/workerpool/dynamic/create/create.go
pkg/cmd/workerpool/dynamic/create/create_test.go
pkg/cmd/workerpool/dynamic/dynamic.go
pkg/cmd/workerpool/shared/view.go
pkg/cmd/workerpool/static/create/create.go
pkg/cmd/workerpool/static/create/create_test.go
pkg/cmd/workerpool/static/static.go
pkg/machinescommon/web.go
pkg/question/input.go

feat:workerpool dynamic create
[sc-29480]
Dynamic pool create, interactive

feat:workerpool static create

---

pkg/cmd/package/list/list.go
pkg/cmd/package/versions/versions.go
pkg/cmd/release/create/create.go
pkg/cmd/release/create/create_test.go
pkg/cmd/runbook/list/list.go

removed inconsistent uses of 'n' for short flag name

---

pkg/cmd/root/help.go
pkg/cmd/target/target.go

fix: fixed padding where sub-commands are > 12

---

pkg/cmd/account/delete/delete.go
pkg/cmd/environment/delete/delete.go
pkg/cmd/project/delete/delete.go
pkg/cmd/projectgroup/delete/delete.go
pkg/cmd/space/delete/delete.go
pkg/question/selectors/selectors.go

chore: remove ids from selector helper

---

pkg/cmd/project/convert/convert.go
pkg/cmd/tenant/clone/clone.go
pkg/cmd/tenant/connect/connect.go
pkg/question/select.go
pkg/question/select_test.go
pkg/surveyext/multiselectwithadd.go

fixes: https://github.com/OctopusDeploy/cli/issues/207
before:
after:
before:
after:

Fix: empty list errors

---

pkg/cmd/project/create/create.go

fixes: https://github.com/OctopusDeploy/cli/issues/212

fix: convert project during creation in automation mode

---

pkg/cmd/project/variables/variables.go

fix: fixed incorrect example

---

.github/workflows/generate-docs.yml
.github/workflows/go-releaser.yml
.github/workflows/integration-test.yml

chore: fix typos in releases.json capture

chore: fix docs pr target branch

---

go.mod
go.sum
pkg/cmd/project/clone/clone.go
pkg/cmd/project/create/create.go
pkg/cmd/project/create/create_opts.go
pkg/cmd/project/create/create_test.go
pkg/cmd/project/project.go
pkg/cmd/project/shared/shared.go
pkg/cmd/project/shared/shared_test.go

Depends upon https://github.com/OctopusDeploy/go-octopusdeploy/pull/194
```
octopus project clone --space "step usages" --name "project 12" --source "project 11" -d "new description" -g "project group"
Successfully cloned project 'project 12' (project-12), with lifecycle 'Lifecycles-183' in project group 'ProjectGroups-203'.
View this project on Octopus Deploy: http://localhost:8065/app#/Spaces-143/projects/Projects-2652
Automation Commands:
octopus project clone --name 'project 12' --source 'project 11' --group 'project group' --lifecycle 'Default Lifecycle' --no-prompt
```
mirroring the project create behaviour for project groups
```
octopus project clone --space "step usages" --name "project 8" --source "project 4" -d "new description"
? You have not specified a Project group for this …
```

feat: project clone

---

.github/workflows/generate-docs.yml
cmd/gen-docs/main.go

Format of the docs site changed significantly, this keeps our generator up-to-date with these changes.

chore: fixed docs gen after docs layout changes

---

.goreleaser.yaml

Based on this example https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L153

missed terminating template if statement

---

.github/workflows/integration-test.yml
go.mod
go.sum
pkg/cmd/account/account.go
pkg/cmd/account/azure-oidc/azure-oidc.go
pkg/cmd/account/azure-oidc/create/create.go
pkg/cmd/account/azure-oidc/create/create_test.go
pkg/cmd/account/azure-oidc/list/list.go
pkg/cmd/account/create/create.go
pkg/cmd/account/list/list.go
pkg/cmd/account/shared/shared.go
test/testutil/fakesurvey.go

feat: account azure-oidc list
list oidc acccounts
```
❯ ./octopus account azure-oidc list
NAME    SLUG    SUBSCRIPTION ID                       AZURE ENVIRONMENT
oidc 2  oidc-2  f328219a-0c05-49e1-805d-b2812608e493  Global Cloud
oidc 5  oidc-5  3a290b2a-0bd7-4882-a672-76610cbbb929  Global Cloud
```
list oidc accounts with json output
```
❯ ./octopus account azure-oidc list -f json
[
{
"Id": "Accounts-223",
"Name": "oidc 2",
"Slug": "oidc-2",
"SubscriptionNumber": "f328219a-0c05-49e1-805d-b2812608e493",
"TenantID": "f328219a-0c05-49e1-805d-b2812608e493",
"ApplicationID": "f328219a-0c05-49e1-805d-b2812608e493",
"AccountType": "AzureOidc",
"AzureEnvironment": "",
"HealthSubjectKeys": [
"space",
"target",
"account",
"type"
],
"TestSubjectKeys": [
"space",
"account",
"type"
], …
```

feat: account azure-oidc create

---

cmd/octopus/main.go

fix: remove requirement for server config on package create commands

---

go.mod
go.sum
pkg/apiclient/apiclient_test.go
pkg/apiclient/client_factory.go
pkg/cmd/account/aws/create/create_test.go
pkg/cmd/account/azure/create/create_test.go
pkg/cmd/account/gcp/create/create_test.go
pkg/cmd/account/ssh/create/create_test.go
pkg/cmd/account/token/create/create_test.go
pkg/cmd/account/username/create/create_test.go
pkg/cmd/login/login.go
pkg/cmd/login/login_test.go
pkg/cmd/package/list/list_test.go
pkg/cmd/package/upload/upload_test.go
pkg/cmd/package/versions/versions_test.go
pkg/cmd/release/create/create_test.go
pkg/cmd/release/delete/delete_test.go
pkg/cmd/release/deploy/deploy_test.go
pkg/cmd/release/list/list_test.go
pkg/cmd/runbook/list/list_test.go

related to https://github.com/OctopusDeploy/go-octopusdeploy/pull/237 and https://github.com/OctopusDeploy/go-octopusdeploy/pull/238
Fixes https://github.com/OctopusDeploy/cli/issues/327
[sc-70983]

fix: support virtual paths during login

---

cmd/octopus/main.go

fix: panic when no arguments and no config

---

.goreleaser.yaml

As per https://github.com/goreleaser/goreleaser/pull/4806

chore: update goreleaser config for breaking change

---

pkg/cmd/buildinformation/build-information.go
pkg/cmd/buildinformation/shared/shared.go
pkg/cmd/buildinformation/view/view.go

view build information
```
octopus build-information view BuildInformation-1000
```
default (table) output
```
$ octopus build-info view BuildInformation-1000
PACKAGE ID    VERSION   ENVIRONMENT  BUILD NO  BRANCH  COMMITS  WORKITEMS
package-6364  0.1.1000  BitBucket    288       main    3        2
```
basic output
```
$ octopus build-info view BuildInformation-1000 --output-format basic
package-6364 0.1.1000 (BuildInformation-1000)
Build details
Environment: BitBucket
Branch: main
URL: https://bitbucket.org/org/repo/addon/pipelines/home#!/results/288
VCS Details
Type: Git
URL: http://bitbucket.org/org/repo
Commit details
Hash: 314cf2c3ee916c92a384c2796a6abe332d678e4f
URL: http://bitbucket.org/org/repo/commits/314cf2c3ee916c92a384c2796a6abe332d678e4f
314cf2c3 MAN-1 - test runbook with …
```

feat: add view build information command

---

go.mod
go.sum
pkg/cmd/project/disable/disable.go
pkg/cmd/project/project.go

feat: add disable project command

---

go.mod
pkg/cmd/project/enable/enable.go
pkg/cmd/project/project.go

feat: add enable project command

---

.github/workflows/integration-test.yml
pkg/cmd/release/deploy/deploy.go
pkg/cmd/runbook/run/run.go

source https://octopusdeploy.slack.com/archives/C03QCL8M4H1/p1722820524090199

chore: extended description for tenant tag names

---

.octopus/deployment_process.ocl

Uses latest worker tools and also uses correct authentication origin

Update homebrew deployment process

---

pkg/cmd/package/nuget/create/create.go
pkg/cmd/package/support/pack.go
pkg/cmd/package/zip/create/create.go

Reverts OctopusDeploy/cli#402
missing conventional commit.

Revert "Print the package that was created"

---

pkg/cmd/package/nuget/create/create.go
pkg/cmd/package/zip/create/create.go

Revert "Removes a whitespace between Path key and value when creating a zip p…"

---

.octopus/deployment_process.ocl

I missed this when copying the command across from the winget-create docs

Fix winget deployment issue

---

.octopus/deployment_process.ocl

Oh PowerShell 🤦 
it picked up the `$version_windows_amd64` as the entire variable...
I double checked it in a VS Code this time to make sure it's valid.

Fix powershell variable reference

---

pkg/cmd/tenant/disable/disable.go

I got the docs wrong again :( sorry.
Updates the disable tenant example.

fix: incorrect disable tenant example

---

.github/workflows/go-releaser.yml

this should now put it in the correct folder 🤞

use the MSI name in the correct folder
